language: c
install: test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
script: bash -ex .travis-ocaml.sh && opam install core core_kernel ppx_compare ppx_inline_test ppx_jane wasm sexplib apron && make test
env:
  - OCAML_VERSION=4.10
os:
  - freebsd
  - linux
  - osx
arch:
  - amd64
