language: c
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get -y install libmpfr-dev
        export GIMME_ARCH=amd64;
    fi

install:
  - test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
  - bash -ex .travis-ocaml.sh
  - opam install -y core core_kernel ppx_compare ppx_inline_test ppx_jane wasm sexplib apron
  - eval $(opam env)

script: make test

env:
  - OCAML_VERSION=4.10
os:
  - freebsd
  - linux
  - osx
arch:
  - amd64

jobs:
  include:
    - stage: test
      name: Tests
      script: make test