name: Compilation and deployment

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.14.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
      - name: Install dependencies
        run: |
          opam install core_unix
          opam install . --deps-only --wiht-doc --with-test
          opam install js_of_ocaml js_of_ocaml-ppx
      - name: Compile binary
        run: make
      - name: Compile web version
        run: |
          make js
          cp ./
      - name: Deploy web version
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: js