name: Compilation on PR

on:
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-version:
          - 4.14.2
          - 5.2.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
      - name: Install dependencies
        run: |
          opam install core_unix
          opam install . --deps-only --with-doc --with-test
      - name: Compile binary
        run: make
      - name: Compile web version
        run: |
          make js
          cp ./
